---
title: "Practice 4 by Gustavo Lima"
output: html_notebook
---

CSV
```{r}

diamonds <- read.csv("diamonds.csv")
str(diamonds)

```
imports
```{r}
library(tidyverse)

```
1.    Graphs

1.1   Dispersion
```{r}
ggplot(diamonds, aes(x=carat,y=price))+
  geom_point()
```
1.2-1.3  color = clarity
```{r}
ggplot(diamonds, aes(x=carat,y=price,color=clarity))+
  geom_point()
```
2.    Histogram
2.1   Price, 40 bins
```{r}
ggplot(diamonds, aes(x=price))+
  geom_histogram(bins=40)
```

2.2   log10 scale
```{r}
ggplot(diamonds, aes(x=price))+
  geom_histogram(bins=40)+
  scale_x_log10()
```
3.    Boxplots
3.1   cut(x) vs price(y), log10 scale
```{r}
ggplot(diamonds, aes(x=cut,y=price))+
  geom_boxplot()+
  scale_y_log10()
```
3.2   fill cut
```{r}
ggplot(diamonds, aes(x=cut,y=price,fill=cut))+
  geom_boxplot()+
  scale_y_log10()
```
4.    Faceting
4.1
```{r}
filtered_price <- diamonds %>%
  filter(price > 1000 & cut%in%c("Good","Ideal","Premium"))

filtered_price

```

4.2   bars, x=cut,y=depth
```{r}
ggplot(filtered_price,aes(x=cut,y=depth))+
  geom_col()
```
4.3   faceting
```{r}
ggplot(filtered_price,aes(x=cut,y=depth))+
  facet_grid(clarity ~ .)+
  geom_col()
```
4.4   fill=clarity

```{r}
ggplot(filtered_price,aes(x=cut,y=depth,fill=clarity))+
  facet_grid(clarity ~ .)+
  geom_col()
```

Grouping and summarizing

1.    group_by(cut),summarize median x,y,z
```{r}
median_dimension_diamond <- diamonds %>%
  group_by(cut) %>%
  summarize(mediaX = mean(x),mediaY =mean(y),mediaZ = mean(z))

median_dimension_diamond
```
2.    filter(cut="Premium"), group_by(clarity),summarize(min and max price)
```{r}
cut_premium <- diamonds %>%
  filter(cut=="Premium") %>%
  group_by(clarity) %>%
  summarize(minPrice = min(price),maxPrice = max(price))

cut_premium
```
3.    Bars Geom, cut_premium, x=clarity, y=maxPrice, fill=clarity
```{r}
ggplot(cut_premium,aes(x=clarity,y=maxPrice,fill=clarity))+
  geom_col()
```

