---
title: "Sesion 4"
output: html_notebook
---

Functions
```{r}
pow_two <- function(x,print_info=TRUE){
  y <- x ^ 2
  if(print_info)
  {
    print(paste(x,"to the power two equals",y))
  }
  return(y)
}
pow_two(3)
```
Function scoping
```{r}
pow_two <- function(x){
  y <- x ^ 2
  return(y)
}
pow_two(4)
y
x
```
R passes arguments by value
```{r}
triple <- function(x){
  x <- 3*x
  x
}
a <- 5
triple(a)
```
other type of parameters
```{r}
linkedin <- c(16,9,13,5,2,17,14)
interpret <- function(num_views){
  if(num_views > 15)
  {
    print("you're popular!")
    return(num_views)
  }else
  {
    print("Try to be more visible")
    return(0)
  }
}
interpret(linkedin[1])

interpret_all <- function(views,return_sum=TRUE)
{
  count <- 0
  for(v in views)
  {
    count <- count + interpret(v)
  }
  if(return_sum)
  {
    return(count)
  }else
  {
    return(NULL)
  }
}

interpret_all(linkedin)
```
Load an R package
```{r}
library(ggplot2)
qplot(mtcars$wt,mtcars$hp)
```
Use Apply with R
lapply
```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

select <- function(x){
  print(mean(x))
}
 list <- lapply(temp,select)
 list
for(t in temp){
  print(min(t))
} 


```
lapply and anonymous functions
```{r}
(function(x,y){3 * x * y})(9,10)

pioneers <- c("GAUSS:1777","BAYES:1702","PASCAL:1623","PEARSON:1857")
split <- strsplit(pioneers,split = ":")

split_low <- lapply(split, tolower)

names <- lapply(split_low, function(x){x[1]})
names

years <- lapply(split_low,function(x){x[2]})
years

```
use lapply with additional arguments
```{r}
select_el <- function(x,index){
  x[index]
}

names <- lapply(split_low,select_el,1)
names

years <- lapply(split_low,select_el,2)
years
```

