---
title: "R Notebook"
Author: "Gustavo Lima"
output: html_notebook
---

1.    Knowing the data

```{r}
library(tidyverse)
yearly <- read.csv("deaths_handwashing.csv")
yearly
```
2.    Alarming death count
```{r}
yearly <- mutate(yearly,proportion_deaths = deaths/births)
yearly
```
3.    Deaths by clinic
```{r}
ggplot(yearly,aes(x=year,y=proportion_deaths, color=clinic,linetype=clinic))+
  geom_line()

```
4.    Starts hand washing
```{r}
monthly <- read.csv("deaths_clinic_1.csv")
monthly

monthly <- mutate(monthly,proportion_deaths = deaths/births)
head(monthly,10)
```
5.    Effect of hands washing
```{r}
ggplot(monthly,aes(x=date,y=proportion_deaths,group=1))+
  geom_line(color="red")+
  labs(title="Hands washing vs death ratio",
       x="Monthly",
       y="Proportion of Deaths",
       caption="Data source: Own elaboration",
       tag="Fig. 2")



```
6.    Results of washing hands
```{r}
monthly <- mutate(monthly,handwashing_started = ifelse(substr(date, 1, 4)>='1847',TRUE,FALSE))
ggplot(monthly,aes(x=date,y=proportion_deaths,color=handwashing_started,group=1))+
  geom_line()+
  labs(title="Hands washing vs death ratio",
       x="Monthly",
       y="Proportion of Deaths",
       subtitle="before and after hand washing started",
       caption="Data source: Own elaboration",
       tag="Fig. 3")



monthly
```

7.    More hands washing, less deaths?
```{r}
month_summary <- monthly %>%
  group_by(handwashing_started)%>%
  summarize(mean_proportion_deaths=mean(proportion_deaths))%>%
  arrange(desc(handwashing_started))

month_summary
```

